import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Providers/Index";
import Navbar from "./Compoent/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CodeTalk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbar/>
          <div>
             {children}
          </div>
        </Provider>
       
        </body>
    </html>
  );
}
